FROM openjdk:21-jdk-slim

RUN addgroup --system spring && adduser --system spring --ingroup spring

COPY target/*.jar app.jar
RUN chown spring:spring app.jar

USER spring:spring
EXPOSE 8082
ENV SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT ["java", "-jar", "/app.jar"]
