FROM maven:3.9.4-amazoncorretto-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

FROM amazoncorretto:21-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Variables d'environnement par défaut
ENV APP_PORT=8082
ENV SPRING_PROFILES_ACTIVE=prod

EXPOSE $APP_PORT

ENTRYPOINT ["java", "-jar", "app.jar"]